"""Paired permutation (randomisation) test.

Under the null hypothesis that the intervention changed nothing, the two arms of an item
are exchangeable: swapping the control and treatment labels for that item leaves the
distribution of the data unchanged. Swapping the labels negates that item's difference,
so the reference distribution is generated by randomly flipping the sign of each item's
paired difference.

The p-value uses the ``(b + 1) / (B + 1)`` form, which counts the observed statistic as
one of its own permutations. Without that correction a Monte-Carlo permutation test can
report p = 0, which is not a valid p-value and makes the test anti-conservative; with it
the test is exactly valid for any number of permutations.

Reference:
    Phipson, B. & Smyth, G. K. (2010). "Permutation p-values should never be zero:
        calculating exact p-values when permutations are randomly drawn."
        Statistical Applications in Genetics and Molecular Biology 9(1):39.
"""

from __future__ import annotations

from typing import Literal, NamedTuple

import numpy as np
import numpy.typing as npt

__all__ = ["DEFAULT_PERMUTATIONS", "PermutationResult", "paired_permutation_test"]

DEFAULT_PERMUTATIONS = 10_000

_MAX_SIGN_ELEMENTS = 4_000_000

# Exhaustive enumeration costs 2**n * n floats. 16 items is 8 MB, which is fine; 22
# items would be 738 MB, which is not.
_MAX_EXACT_ITEMS = 16

Alternative = Literal["two-sided", "greater", "less"]


class PermutationResult(NamedTuple):
    observed: float
    p_value: float
    permutations: int
    alternative: Alternative
    exact: bool
    """True when every sign assignment was enumerated rather than sampled."""


def _sign_matrix(n: int, size: int, rng: np.random.Generator) -> npt.NDArray[np.float64]:
    return rng.integers(0, 2, size=(size, n)).astype(np.float64) * 2.0 - 1.0


def _exact_sign_matrix(n: int) -> npt.NDArray[np.float64]:
    """All 2**n sign vectors, for small n where exhaustive enumeration is cheap."""
    codes = np.arange(2**n, dtype=np.uint32)[:, None]
    bits = (codes >> np.arange(n, dtype=np.uint32)) & 1
    return bits.astype(np.float64) * 2.0 - 1.0


def paired_permutation_test(
    control: npt.ArrayLike,
    treatment: npt.ArrayLike,
    *,
    permutations: int = DEFAULT_PERMUTATIONS,
    alternative: Alternative = "two-sided",
    seed: int | None = None,
) -> PermutationResult:
    """Test whether ``mean(treatment - control)`` differs from zero.

    Args:
        control: per-item control scores.
        treatment: per-item treatment scores, aligned with ``control``.
        permutations: number of random sign assignments to draw. If the item set is
            small enough that ``2**n_items <= permutations``, every assignment is
            enumerated instead and the p-value is exact.
        alternative: ``"two-sided"``, ``"greater"`` (treatment beats control) or
            ``"less"``.
        seed: RNG seed for the sampled case.

    Returns:
        PermutationResult; ``p_value`` is never below ``1 / (permutations + 1)``.
    """
    control_array = np.asarray(control, dtype=np.float64)
    treatment_array = np.asarray(treatment, dtype=np.float64)
    if control_array.shape != treatment_array.shape:
        raise ValueError(
            f"control and treatment must be aligned per item; got shapes "
            f"{control_array.shape} and {treatment_array.shape}"
        )
    if control_array.ndim != 1 or control_array.size == 0:
        raise ValueError("control and treatment must be non-empty one-dimensional arrays")
    if permutations < 1:
        raise ValueError(f"permutations must be >= 1, got {permutations!r}")
    if alternative not in ("two-sided", "greater", "less"):
        raise ValueError(f"unknown alternative {alternative!r}")

    differences = treatment_array - control_array
    if not np.all(np.isfinite(differences)):
        raise ValueError("control/treatment contain non-finite values")

    n = differences.size
    observed = float(differences.mean())

    exact = n <= _MAX_EXACT_ITEMS and 2**n <= permutations
    if exact:
        signs = _exact_sign_matrix(n)
        draws = signs @ differences / n
        n_draws = draws.size
    else:
        chunk = max(1, min(permutations, _MAX_SIGN_ELEMENTS // n))
        rng = np.random.default_rng(seed)
        draws = np.empty(permutations, dtype=np.float64)
        done = 0
        while done < permutations:
            size = min(chunk, permutations - done)
            draws[done : done + size] = _sign_matrix(n, size, rng) @ differences / n
            done += size
        n_draws = permutations

    if alternative == "two-sided":
        # Strict-greater would let a tie at exactly the observed value count as evidence
        # against the null. Paired 0/1 scores produce those ties constantly, so ">=" it
        # is; the test is conservative under heavy ties, which is the safe direction.
        at_least_as_extreme = int(np.count_nonzero(np.abs(draws) >= abs(observed) - 1e-12))
    elif alternative == "greater":
        at_least_as_extreme = int(np.count_nonzero(draws >= observed - 1e-12))
    else:
        at_least_as_extreme = int(np.count_nonzero(draws <= observed + 1e-12))

    # Exhaustive enumeration already contains the observed assignment (all +1), so its
    # ratio is the exact randomisation p-value with nothing to add. A sampled run may
    # not have drawn it, hence the (b+1)/(B+1) correction.
    p_value = at_least_as_extreme / n_draws if exact else (at_least_as_extreme + 1) / (n_draws + 1)

    return PermutationResult(
        observed=observed,
        p_value=min(1.0, p_value),
        permutations=n_draws,
        alternative=alternative,
        exact=exact,
    )
