#!/usr/bin/env python3
"""Regenerate ``tests/fixtures/foreign_tool_results/``.

SYNTHETIC. Every number in that directory was generated by this script from a seeded
RNG. Nothing in it was produced by a language model, and it is not a measurement of
anything (SHARED-FOUNDATION D3: a synthetic fixture is never presented as a result).

It exists to test one specific claim: that ``errorbars analyze`` reads a CXS results
directory written by **some other tool**, not just its own output. So it deliberately
differs from what ``errorbars run`` writes, in every way a conformant tool is allowed
to differ:

* ``tool.name`` is a fictional third-party tool, not errorbars;
* the arms are named ``baseline`` / ``shuffle-context`` / ``drop-tool-schemas`` -- none
  of which errorbars would ever generate;
* outcomes carry ``passed`` booleans with **no** ``score`` field;
* the manifest has no ``control_intervention_id``, so the control must be found from
  ``kind: "noop"`` in ``interventions.json``;
* every object carries extra fields errorbars has never heard of
  (``run_group``, ``harness_seed``, ``judge_notes``, ``wall_clock``);
* trial ids use a different format entirely.

Run with:  python tests/fixtures/make_foreign_fixture.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path

SEED = 4242
N_ITEMS = 80
REPEATS = 3

# True per-arm behaviour built into the fixture, so the test knows what the right answer
# looks like: shuffling context costs about 20 points, dropping tool schemas costs
# nothing at all.
ARMS = {
    "baseline": 0.0,
    "shuffle-context": -0.20,
    "drop-tool-schemas": 0.0,
}

OUT = Path(__file__).parent / "foreign_tool_results"


def main() -> None:
    rng = random.Random(SEED)
    OUT.mkdir(parents=True, exist_ok=True)

    # Per-item difficulty, shared across arms: this is what makes the run paired, and it
    # gives the fixture a realistic ICC and pairing correlation rather than zero.
    difficulty = {f"task-{index:03d}": rng.uniform(0.55, 0.98) for index in range(N_ITEMS)}

    trials = []
    outcomes = []
    counter = 0
    for arm, delta in ARMS.items():
        for item_id, base in difficulty.items():
            probability = min(1.0, max(0.0, base + delta))
            for repeat in range(REPEATS):
                counter += 1
                trial_id = f"cp-{counter:06d}"
                passed = rng.random() < probability
                trials.append(
                    {
                        "trial_id": trial_id,
                        "experiment_id": "cp-2026-09-02-tooluse",
                        "intervention_id": arm,
                        "item_id": item_id,
                        "repeat_index": repeat,
                        "model": {
                            "provider": "openai-compatible",
                            "base_url": "http://localhost:11434/v1",
                            "model": "example-8b",
                            "params": {"temperature": 0.0, "max_tokens": 256, "seed": None},
                            "observed_at": "2026-09-02T11:04:00Z",
                        },
                        "prompt_sha256": f"{rng.getrandbits(256):064x}",
                        "response_text": "call get_user" if passed else "call delete_user",
                        "cached": rng.random() < 0.3,
                        "latency_ms": rng.randint(300, 1800),
                        "usage": {
                            "prompt_tokens": rng.randint(500, 900),
                            "completion_tokens": rng.randint(5, 40),
                        },
                        "error": None,
                        "observed_at": "2026-09-02T11:04:00Z",
                        # Fields errorbars has never heard of. A conformant reader
                        # ignores them rather than refusing the file.
                        "run_group": "tool-selection",
                        "harness_seed": 4242,
                        "wall_clock": 1.23,
                    }
                )
                outcomes.append(
                    {
                        "trial_id": trial_id,
                        "scorer": "tool_name_match:v2",
                        # No 'score' field at all: this tool only records pass/fail, and
                        # errorbars has to cope with that.
                        "passed": passed,
                        "detail": {"expected_tool": "get_user"},
                        "judge_notes": "",
                    }
                )

    (OUT / "trials.jsonl").write_text(
        "".join(json.dumps(record) + "\n" for record in trials), encoding="utf-8"
    )
    (OUT / "outcomes.jsonl").write_text(
        "".join(json.dumps(record) + "\n" for record in outcomes), encoding="utf-8"
    )
    (OUT / "interventions.json").write_text(
        json.dumps(
            [
                {
                    "id": "baseline",
                    "kind": "noop",
                    "description": "Unmodified context.",
                    "deterministic": True,
                    "implementation": "contextprobe.arms.baseline:v2",
                },
                {
                    "id": "shuffle-context",
                    "kind": "reorder",
                    "selector": {"type": "document_order", "value": "shuffle"},
                    "description": "Randomise the order of retrieved documents.",
                    "deterministic": False,
                    "implementation": "contextprobe.arms.shuffle:v2",
                },
                {
                    "id": "drop-tool-schemas",
                    "kind": "remove",
                    "selector": {"type": "unit_kind", "value": "tool_schema"},
                    "description": "Remove unused tool schemas from the request.",
                    "deterministic": True,
                    "implementation": "contextprobe.arms.drop_schemas:v2",
                },
            ],
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (OUT / "manifest.json").write_text(
        json.dumps(
            {
                "cxs_version": "0.1",
                "experiment_id": "cp-2026-09-02-tooluse",
                # Not errorbars. That is the whole point of this fixture.
                "tool": {"name": "contextprobe", "version": "2.4.0"},
                "created_at": "2026-09-02T11:00:00Z",
                "models": [
                    {
                        "provider": "openai-compatible",
                        "base_url": "http://localhost:11434/v1",
                        "model": "example-8b",
                        "params": {"temperature": 0.0, "max_tokens": 256, "seed": None},
                        "observed_at": "2026-09-02T11:00:00Z",
                    }
                ],
                "dataset": {
                    "name": "tool-selection-synthetic",
                    "sha256": "0" * 64,
                    "n_items": N_ITEMS,
                    "source": "synthetic fixture, generated by make_foreign_fixture.py",
                },
                "scorer": "tool_name_match:v2",
                "repeats": REPEATS,
                "seed": SEED,
                "determinism": "stochastic",
                "cache": {"hits": 0, "misses": len(trials)},
                "totals": {
                    "model_calls": len(trials),
                    "prompt_tokens": sum(t["usage"]["prompt_tokens"] for t in trials),
                    "completion_tokens": sum(t["usage"]["completion_tokens"] for t in trials),
                },
                "environment": {"python": "3.12.3", "platform": "linux"},
                # No control_intervention_id: errorbars has to find the control from
                # interventions.json.
                "notes": (
                    "SYNTHETIC FIXTURE. Generated by "
                    "tests/fixtures/make_foreign_fixture.py from a seeded RNG. Not a "
                    "measurement of any model. Written in the style of a third-party "
                    "tool to test cross-tool ingestion."
                ),
                "harness_config": {"retries": 2, "concurrency": 8},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(trials)} trials and {len(outcomes)} outcomes to {OUT}")


if __name__ == "__main__":
    main()
